### ISSUE TITLE
`assess_region()` and `site_assess_region()` functions don't seem to use cache when running a request a second time. 

### ISSUE THREAD

**Issue by BG-AIMS** [open-AIMS/ReefGuideAPI.jl#31]
These functions don seem to store or don't access assessment results that have been processed already.
Running these example links a second time doesn't seem to access the results data from the initial run from cache. 

`127.0.0.1:8000/suitability/assess/Cairns-Cooktown/slopes?Depth=-4.0:-2.0&Slope=0.0:40.0&Rugosity=0.0:6.0` OR 
`127.0.0.1:8000/suitability/site-suitability/Cairns-Cooktown/slopes?Depth=-4.0:-2.0&Slope=0.0:40.0&Rugosity=0.0:6.0&SuitabilityThreshold=95&xdist=450&ydist=50`

**Comment by ConnectedSystems** [comment]
As noted in discussion, caching was not implemented hence why the results were not being saved from the initial query.

This is now implemented in #32
