### ISSUE TITLE
Cache to disk server cold start

### ISSUE THREAD

**Issue by PeterBaker0** [open-AIMS/ReefGuideAPI.jl#8]
Currently for dockerisation there is a severe cold start to run the container. 

If possible, it would be ideal to cache to disk the output of this cold starting so that when another session is launched, the server can start immediately. 

An interface could be 

```
$> julia
julia> using ReefGuideAPI.jl
julia> ReefGuideAPI.jl.warm() // incurs cold start then closes process
julia> exit() 
$> julia
julia> using ReefGuideAPI.jl
julia> ReefGuideAPI.jl.start_server("config/path") // no cold start, uses disk cache
```

This way we could add a layer to the docker file which pre-builds this cache, decreasing cold start times significantly.

**Comment by arlowhite** [comment]
If this cache is tied to the data, and we manage the data separately, then it can't be a Docker layer, right?

**Comment by PeterBaker0** [comment]
True - if the cold-start time is incurred by a process which requires mounted data to run, then it can't be embedded into the layer. However if the container has r/w into the data volume and can output the file cache, then other containers can pick this up in our context (EFS) and avoid doing this again.
